version: "3.8"

volumes:
  geoserver-data:
  geo-db-data:

services:
  db:
    build: ./db/postgis
    container_name: ldes-postgis
    environment:
      POSTGRES_DB: mobility_hindrance
      POSTGRES_USER: ldes
      POSTGRES_PASSWORD: ldes
    volumes:
        - geo-db-data:/var/lib/postgresql
    ports:
      - 5432:5432
  dba:
    image: dpage/pgadmin4:latest
    container_name: ldes-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ldes@ldes.be
      PGADMIN_DEFAULT_PASSWORD: ldes
    ports:
      - 8001:80
    depends_on:
      - db
    links:
      - db
  geoserver:
    build: ./geoserver
    container_name: ldes-postgis-geoserver
    ports:
      - 8002:8080
    environment:
      - GEOSERVER_ADMIN_PASSWORD=ldes
      - GEOSERVER_ADMIN_USER=ldes
    depends_on:
      - db
  app:
    build: .
    container_name: ldes-app
    environment:
      DB_TYPE: postgis
      DB_PORT: 5432
      DB_USER: ldes
      DB_PASSWORD: ldes
      DB_HOST: db
      DB_DATABASE: mobility_hindrance
    depends_on:
      - db